"""Added price to Mustang class.

Revision ID: 341f87e8b993
Revises: a05521192586
Create Date: 2024-03-27 16:44:40.853975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341f87e8b993'
down_revision = 'a05521192586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mustangs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mustangs', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
