"""Add image field to Mustang model

Revision ID: 5143b4f78aa7
Revises: 341f87e8b993
Create Date: 2024-03-27 19:54:37.304445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5143b4f78aa7'
down_revision = '341f87e8b993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mustangs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mustangs', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
